#
# Reference
# https://bukkit.gamepedia.com/Plugin_YAML
#
name: EscapeRoom
main: net.peacefulcraft.escaperoom.EscapeRoom
version: 0.0.1
api-version: 1.16
website: https://www.peacefulcraft.net/
depend: []
softdepend: []

commands:
  escaperoomadmin:
    aliases: [ 'esa' ]
    description: Escape room admin command
    permission-message:  The escaperoom.admin permission is required to use this command.
    usage: /<command> to use the example command.

permissions:
  escaperoom.*:
    description: Gives access to all non-admin escape room commands
  escaperoom.admin:
    description: Gives access to all escape room administrative commands
    default: op
